import {
  ANKLE_LIGAMENT_TOPOGRAPHY_DIRECTIVE,
  KIDNEY_URINARY_TOPOGRAPHY_DIRECTIVE,
  ABDOMINAL_WALL_TOPOGRAPHY_DIRECTIVE,
  SCROTUM_TOPOGRAPHY_DIRECTIVE,
  MUSCLE_TENDON_TOPOGRAPHY_DIRECTIVE,
  WRIST_TOPOGRAPHY_DIRECTIVE,
  buildShoulderDirectivesFromScorecard,
  buildAnkleDirectivesFromScorecard,
  buildKidneyDirectivesFromScorecard,
  buildThyroidDirectivesFromScorecard,
  buildBreastDirectivesFromScorecard,
  buildAbdominalWallDirectivesFromScorecard,
  buildScrotumDirectivesFromScorecard,
  buildMuscleTendonDirectivesFromScorecard,
  buildWristDirectivesFromScorecard,
  buildVascularDirectivesFromScorecard,
} from "./clinicalIntelligence";
import {
  OrganSuiteConfig,
  detectByKeywords,
  genericAttach,
  genericSuggestMore,
} from "./organSuiteConfig";

export const shoulderSuiteConfig: OrganSuiteConfig = {
  id: "shoulder",
  accent: "amber",
  title: "Suite Hombro 3D & Ficha Manguito Rotador",
  badge: "MSK Pro",
  subtitle: "Reconstrucción 3D del manguito, TCLB, bursa y correlación dinámico-funcional",
  studyTypeLabel: "Tipo de estudio de hombro",
  studyTypes: [
    { value: "hombro_b_mode", label: "Hombro B-mode" },
    { value: "hombro_doppler", label: "Hombro + Doppler" },
    { value: "hombro_manguito", label: "Manguito rotador / TCLB" },
    { value: "general_shoulder", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        { value: "hombro_manguito", keys: ["manguito", "rotator", "supraespin"] },
        { value: "hombro_doppler", keys: ["doppler"] },
        { value: "hombro_b_mode", keys: ["hombro", "shoulder"] },
      ],
      "general_shoulder"
    ),
  studyTypeBodyKey: "shoulderType",
  generateUrl: "/api/generate-3d-shoulder",
  regenerateUrl: "/api/regenerate-3d-shoulder-panel",
  taskId: "shoulder-3d",
  taskTitle: "Generando Suite Hombro 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD HOMBRO",
  scorecardBadge: "Scorecard hombro obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar manguito si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: "",
  buildScorecardDirectives: buildShoulderDirectivesFromScorecard,
  directivesPlaceholder: "Ej: Destacar rotura parcial bursal del supraespinoso derecho...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla del manguito",
  loadingDetail: "Renderizando anatomía del manguito, bursa y correlación dinámico-funcional.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D del Hombro (${n} Paneles)`,
  fichaTitle: "Ficha clínica hombro / manguito",
  summaryLabel: "Resumen del hombro",
  summaryField: "shoulderSummary",
  morphologyLabel: "Morfología / tendón dominante",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Estado del manguito",
  domainStatusField: "cuffStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-emerald-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA DE HOMBRO",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D HOMBRO Y CORRELACIÓN MANGUITO ROTADOR",
  defaultTableTitle: "TABLA ECOGRÁFICA DEL MANGUITO ROTADOR:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA Y FUNCIONAL DEL MANGUITO:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN",
    "ESTRUCTURA",
    "GROSOR / GAP",
    "PATRÓN ECO",
    "BURSA",
    "DINÁMICA",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "structure",
    "thicknessOrGap",
    "echoPattern",
    "bursalStatus",
    "dynamicFinding",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Hombro",
    structure: "Supraespinoso",
    thicknessOrGap: "—",
    echoPattern: "Patrón fibrilar",
    bursalStatus: "Sin distensión",
    dynamicFinding: "Sin pinzamiento",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "location"],
  annotationSizeKeys: ["sizeOrThickness", "size"],
  regenPlaceholder: "Ej: Mostrar gap completo del supraespinoso...",
  noReportError: "No hay informe disponible para procesar la suite de hombro.",
  analyzingStep: "Analizando manguito rotador y estructuras periarticulares...",
  buildingStep: "Construyendo paneles 3D y ficha del manguito...",
  syncedLabel: (n) => `Suite Hombro 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Hombro 3D con IA",
  regenerateLabel: "Re-generar Suite Hombro Completa",
  processingLabel: "Procesando Suite Hombro...",
  suggestTitle: "Propone etiquetas desde la ficha del manguito",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
};

export const ankleSuiteConfig: OrganSuiteConfig = {
  id: "ankle",
  accent: "lime",
  title: "Suite Tobillo 3D & Ficha Ligamentos y Aquiles",
  badge: "MSK Pro",
  subtitle:
    "Reconstrucción 3D de ligamentos laterales/mediales, tendón de Aquiles, derrame y correlación dinámico-funcional",
  studyTypeLabel: "Tipo de estudio de tobillo",
  studyTypes: [
    { value: "tobillo_completo", label: "Tobillo completo" },
    { value: "aquiles_tendon", label: "Tendón de Aquiles" },
    { value: "tobillo_ligamentos", label: "Ligamentos laterales y mediales" },
    { value: "general_tobillo", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        { value: "aquiles_tendon", keys: ["aquiles", "achilles"] },
        {
          value: "tobillo_ligamentos",
          keys: ["ligamento", "atfl", "lpaa", "cfl", "lpc", "deltoid", "deltoides", "sindesmosis"],
        },
        { value: "tobillo_completo", keys: ["tobillo", "ankle"] },
      ],
      "general_tobillo"
    ),
  studyTypeBodyKey: "ankleType",
  generateUrl: "/api/generate-3d-ankle",
  regenerateUrl: "/api/regenerate-3d-ankle-panel",
  taskId: "ankle-3d",
  taskTitle: "Generando Suite Tobillo 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD TOBILLO",
  scorecardBadge: "Scorecard tobillo obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar de Aquiles / trauma de tobillo si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: ANKLE_LIGAMENT_TOPOGRAPHY_DIRECTIVE,
  buildScorecardDirectives: buildAnkleDirectivesFromScorecard,
  directivesPlaceholder:
    "Ej: Complejo LATERAL (peroné) LPAA/ATFL derecho — no confundir con deltoides/medial...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla de ligamentos/Aquiles",
  loadingDetail: "Renderizando ligamentos, Aquiles, derrame y correlación dinámico-funcional.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D del Tobillo (${n} Paneles)`,
  fichaTitle: "Ficha clínica tobillo / ligamentos-Aquiles",
  summaryLabel: "Resumen del tobillo",
  summaryField: "ankleSummary",
  morphologyLabel: "Morfología / notas estructurales",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Estado ligamentos / Aquiles",
  domainStatusField: "ligamentAchillesStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-emerald-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA DE TOBILLO",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D TOBILLO Y CORRELACIÓN LIGAMENTOS / AQUILES",
  defaultTableTitle: "TABLA ECOGRÁFICA DE LIGAMENTOS Y AQUILES:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA Y FUNCIONAL DEL TOBILLO:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN",
    "ESTRUCTURA",
    "GROSOR / GAP",
    "PATRÓN ECO",
    "DERRAME",
    "DINÁMICA",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "structure",
    "thicknessOrGap",
    "echoPattern",
    "effusionStatus",
    "dynamicFinding",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Tobillo",
    structure: "LPAA / ATFL",
    thicknessOrGap: "—",
    echoPattern: "Patrón fibrilar",
    effusionStatus: "Sin distensión",
    dynamicFinding: "Sin inestabilidad dinámica",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "location"],
  annotationSizeKeys: ["sizeOrThickness", "size"],
  regenPlaceholder: "Ej: LPAA/ATFL LATERAL (peroné) — no intercambiar con deltoides medial...",
  noReportError: "No hay informe disponible para procesar la suite de tobillo.",
  analyzingStep: "Analizando ligamentos, Aquiles y estructuras periarticulares...",
  buildingStep: "Construyendo paneles 3D y ficha de ligamentos/Aquiles...",
  syncedLabel: (n) => `Suite Tobillo 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Tobillo 3D con IA",
  regenerateLabel: "Re-generar Suite Tobillo Completa",
  processingLabel: "Procesando Suite Tobillo...",
  suggestTitle: "Propone etiquetas desde la ficha de ligamentos/Aquiles",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
};

export const kidneySuiteConfig: OrganSuiteConfig = {
  id: "kidney",
  accent: "teal",
  title: "Suite Riñón 3D & Ficha Vías Urinarias",
  badge: "Renal Pro",
  subtitle: "Reconstrucción 3D de riñones, sistema colector, litiasis/quistes y vejiga",
  studyTypeLabel: "Tipo de estudio renal",
  studyTypes: [
    { value: "renal_b_mode", label: "Renal B-mode" },
    { value: "renal_doppler", label: "Renal + Doppler" },
    { value: "vias_urinarias", label: "Vías urinarias / vejiga" },
    { value: "general_kidney", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        {
          value: "vias_urinarias",
          keys: ["vejiga", "ureter", "uréter", "vias urin", "vías urin", "prostat"],
        },
        { value: "renal_doppler", keys: ["doppler", "resistiv", "arteria renal"] },
        {
          value: "renal_b_mode",
          keys: ["riñon", "riñón", "renal", "kidney", "hidronef", "bosniak", "litiasis"],
        },
      ],
      "general_kidney"
    ),
  studyTypeBodyKey: "kidneyType",
  generateUrl: "/api/generate-3d-kidney",
  regenerateUrl: "/api/regenerate-3d-kidney-panel",
  taskId: "kidney-3d",
  taskTitle: "Generando Suite Riñón 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD RENAL",
  scorecardBadge: "Scorecard renal obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar renal / vías urinarias si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: KIDNEY_URINARY_TOPOGRAPHY_DIRECTIVE,
  buildScorecardDirectives: buildKidneyDirectivesFromScorecard,
  directivesPlaceholder:
    "Ej: Riñón DERECHO con ectasia grado II — no intercambiar con izquierdo; Bosniak II en polo superior...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla renal / vías urinarias",
  loadingDetail: "Renderizando anatomía renal, sistema colector, litiasis/quistes y vejiga.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D Renal (${n} Paneles)`,
  fichaTitle: "Ficha clínica renal / vías urinarias",
  summaryLabel: "Resumen renal",
  summaryField: "kidneySummary",
  morphologyLabel: "Morfología / ecoestructura",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Estado de vías urinarias",
  domainStatusField: "urinaryTractStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-emerald-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA RENAL Y VÍAS URINARIAS",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D RENAL Y CORRELACIÓN VÍAS URINARIAS",
  defaultTableTitle: "TABLA ECOGRÁFICA RENAL Y VÍAS URINARIAS:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA Y FUNCIONAL RENAL:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN",
    "ESTRUCTURA",
    "TAMAÑO / GROSOR",
    "PATRÓN ECO",
    "HIDRONEFROSIS",
    "QUISTE / LITIASIS",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "structure",
    "sizeOrThickness",
    "echoPattern",
    "hydronephrosis",
    "cystOrStone",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Riñón",
    structure: "Corteza / seno renal",
    sizeOrThickness: "—",
    echoPattern: "Ecoestructura conservada",
    hydronephrosis: "Sin ectasia",
    cystOrStone: "Sin quistes ni litiasis",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "location"],
  annotationSizeKeys: ["sizeOrThickness", "size"],
  regenPlaceholder:
    "Ej: Riñón IZQUIERDO, pelvis — grado de ectasia y litiasis exactos según informe...",
  noReportError: "No hay informe disponible para procesar la suite renal.",
  analyzingStep: "Analizando riñones y riñones y estructuras periarticulares...",
  buildingStep: "Construyendo paneles 3D y ficha renal / vías urinarias...",
  syncedLabel: (n) => `Suite Riñón 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Riñón 3D con IA",
  regenerateLabel: "Re-generar Suite Riñón Completa",
  processingLabel: "Procesando Suite Riñón...",
  suggestTitle: "Propone etiquetas desde la ficha renal",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
};

export const thyroidSuiteConfig: OrganSuiteConfig = {
  id: "thyroid",
  accent: "teal",
  title: "Suite Tiroides 3D & Ficha TI-RADS",
  badge: "Cervical Pro",
  subtitle:
    "Reconstrucción macrotiroides 3D de alta fidelidad, cálculo de estenosis y tabulación de velocidades",
  studyTypeLabel: "Tipo de estudio tiroideo",
  studyTypes: [
    { value: "tiroides_b_mode", label: "Tiroides B-mode / nódulos" },
    { value: "tiroides_doppler", label: "Tiroides + Doppler" },
    { value: "tiroides_nodos", label: "Tiroides + ganglios cervicales" },
    { value: "general_thyroid", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        { value: "tiroides_nodos", keys: ["ganglio", "cervical"] },
        { value: "tiroides_doppler", keys: ["doppler"] },
        { value: "tiroides_b_mode", keys: ["tiroid", "tirads", "ti-rads"] },
      ],
      "general_thyroid"
    ),
  studyTypeBodyKey: "thyroidType",
  generateUrl: "/api/generate-3d-thyroid",
  regenerateUrl: "/api/regenerate-3d-thyroid-panel",
  taskId: "thyroid-3d",
  taskTitle: "Generando Suite Tiroides 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD TIROIDES",
  scorecardBadge: "Scorecard vascular obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard se inyectan siempre como directiva obligatoria (igual que Atlas / Focal 3D).",
  topographyDirective: "",
  buildScorecardDirectives: buildThyroidDirectivesFromScorecard,
  directivesPlaceholder: "Ej: Destacar placa ulcerada en bulbo derecho...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla velocimétrica",
  loadingDetail:
    "Renderizando modelos anatómicos fotorrealistas de los vasos, caracterizando placas y sintetizando índices hemodinámicos.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D de Vasos (${n} Paneles)`,
  fichaTitle: "Ficha clínica tiroidea",
  summaryLabel: "Resumen glandular",
  summaryField: "glandSummary",
  morphologyLabel: "Morfología / nódulo dominante",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Ganglios cervicales",
  domainStatusField: "nodalStatus",
  domainStatusAccent: "text-amber-300",
  keyPointsAccent: "text-emerald-300",
  hasKeyPoints: true,
  defaultTerritory: "DOPPLER VASCULAR",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D DE CORRELACIÓN ANATOMOPATOLÓGICA Y HEMODINÁMICA",
  defaultTableTitle: "TABLA TI-RADS Y CARACTERIZACIÓN DE LESIONES:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA Y TI-RADS:",
  tableProperty: "noduleTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN",
    "COMPOSICIÓN",
    "TAMAÑO",
    "ECOGENICIDAD",
    "MÁRGENES",
    "FOCOS",
    "TI-RADS",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "composition",
    "size",
    "echogenicity",
    "margins",
    "echogenicFoci",
    "tiradsCategory",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Lóbulo / istmo",
    size: "—",
    composition: "Sólido",
    echogenicity: "Isoecoico",
    margins: "Bien definidos",
    echogenicFoci: "Ninguno",
    tiradsCategory: "TR2",
    clinicalImpact: "Seguimiento",
  },
  annotationTextKeys: ["location", "composition", "echogenicity"],
  annotationSizeKeys: ["size"],
  regenPlaceholder: "Ej: Mostrar trombo oclusivo más oscuro...",
  noReportError: "No hay informe disponible para procesar el mapa tiroideo.",
  analyzingStep: "Analizando parámetros velocimétricos y estudio tiroideo...",
  buildingStep: "Construyendo matriz hemodinámica y prompts macro-vasculares 3D...",
  syncedLabel: (n) => `Suite Tiroides 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Tiroides 3D con IA",
  regenerateLabel: "Re-generar Suite Tiroides Completa",
  processingLabel: "Procesando Suite Tiroides...",
  suggestTitle: "Propone etiquetas desde la tabla TI-RADS",
  attachSuggestions: (d) =>
    genericAttach(d, "noduleTable", ["location", "composition", "echogenicity"], ["size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "noduleTable", ["location", "composition", "echogenicity"], ["size"]),
};

export const breastSuiteConfig: OrganSuiteConfig = {
  id: "breast",
  accent: "pink",
  title: "Suite Mama 3D & Ficha BI-RADS",
  badge: "Mama Pro",
  subtitle: "Reconstrucción 3D mamaria, caracterización BI-RADS y correlación axilar",
  studyTypeLabel: "Tipo de estudio mamario",
  studyTypes: [
    { value: "mama_b_mode", label: "Mama B-mode / nódulos" },
    { value: "mama_doppler", label: "Mama + Doppler" },
    { value: "mama_axilas", label: "Mama + axilas" },
    { value: "general_breast", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        { value: "mama_axilas", keys: ["axil"] },
        { value: "mama_doppler", keys: ["doppler", "vascularidad"] },
        { value: "mama_b_mode", keys: ["mama", "birads", "bi-rads", "breast"] },
      ],
      "general_breast"
    ),
  studyTypeBodyKey: "breastType",
  generateUrl: "/api/generate-3d-breast",
  regenerateUrl: "/api/regenerate-3d-breast-panel",
  taskId: "breast-3d",
  taskTitle: "Generando Suite Mama 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD MAMA",
  scorecardBadge: "Scorecard BI-RADS obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard BI-RADS se inyectan siempre como directiva obligatoria (igual que Atlas / Tiroides / Hombro).",
  topographyDirective: "",
  buildScorecardDirectives: buildBreastDirectivesFromScorecard,
  directivesPlaceholder: "Ej: Destacar nódulo sólido irregular en 3h de mama derecha...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla velocimétrica",
  loadingDetail:
    "Renderizando modelos anatómicos fotorrealistas de los vasos, caracterizando placas y sintetizando índices hemodinámicos.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D de Vasos (${n} Paneles)`,
  fichaTitle: "Ficha clínica mamaria",
  summaryLabel: "Resumen mamario",
  summaryField: "breastSummary",
  morphologyLabel: "Morfología / lesión dominante",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Axilas / drenaje",
  domainStatusField: "axillaryStatus",
  domainStatusAccent: "text-amber-300",
  keyPointsAccent: "text-emerald-300",
  hasKeyPoints: true,
  defaultTerritory: "DOPPLER VASCULAR",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D DE CORRELACIÓN ANATOMOPATOLÓGICA Y HEMODINÁMICA",
  defaultTableTitle: "TABLA BI-RADS Y CARACTERIZACIÓN DE LESIONES:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA Y BI-RADS:",
  tableProperty: "lesionTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN (RELOJ)",
    "COMPOSICIÓN",
    "TAMAÑO",
    "ECO",
    "MÁRGENES",
    "ORIENTACIÓN",
    "VASCULARIDAD",
    "BI-RADS",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "composition",
    "size",
    "echogenicity",
    "margins",
    "orientation",
    "vascularity",
    "biradsCategory",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Mama derecha, 12h",
    size: "—",
    composition: "Sólida",
    shape: "Oval",
    margins: "Circunscritos",
    echogenicity: "Hipoecoico",
    orientation: "Paralelo",
    vascularity: "Ausente / periférico",
    biradsCategory: "BI-RADS 3",
    clinicalImpact: "Seguimiento",
  },
  annotationTextKeys: ["location", "shape", "echogenicity"],
  annotationSizeKeys: ["size"],
  regenPlaceholder: "Ej: Mama derecha eje 10 (CSE) — NO eje 2...",
  noReportError: "No hay informe disponible para procesar el mapa tiroideo.",
  analyzingStep: "Analizando parámetros velocimétricos y estudio tiroideo...",
  buildingStep: "Construyendo matriz hemodinámica y prompts macro-vasculares 3D...",
  syncedLabel: (n) => `Suite Mama 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Mama 3D con IA",
  regenerateLabel: "Re-generar Suite Mama Completa",
  processingLabel: "Procesando Suite Mama...",
  suggestTitle: "Propone etiquetas desde la tabla BI-RADS",
  attachSuggestions: (d) =>
    genericAttach(d, "lesionTable", ["location", "shape", "echogenicity"], ["size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "lesionTable", ["location", "shape", "echogenicity"], ["size"]),
};

export const abdominalWallSuiteConfig: OrganSuiteConfig = {
  id: "abdominal-wall",
  accent: "amber",
  title: "Suite Pared Abdominal 3D & Ficha de Pared",
  badge: "Pared Pro",
  subtitle: "Reconstrucción 3D de hernias, diástasis, capas fasciales y dinámica con Valsalva",
  studyTypeLabel: "Tipo de estudio de pared abdominal",
  studyTypes: [
    { value: "hernia_inguinal_crural", label: "Hernia inguinal / crural" },
    { value: "hernia_umbilical_epigastrica", label: "Hernia umbilical / epigástrica" },
    { value: "diastasis_recto_eventracion", label: "Diástasis de rectos / eventración" },
    { value: "general_pared_abdominal", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        { value: "hernia_inguinal_crural", keys: ["inguinal", "crural", "femoral", "ingle"] },
        {
          value: "hernia_umbilical_epigastrica",
          keys: ["umbilical", "epigastr", "linea alba", "línea alba"],
        },
        {
          value: "diastasis_recto_eventracion",
          keys: ["diastasis", "diástasis", "eventracion", "eventración", "recto abdominal"],
        },
        { value: "general_pared_abdominal", keys: ["pared abdominal", "hernia", "valsalva"] },
      ],
      "general_pared_abdominal"
    ),
  studyTypeBodyKey: "abdominalWallType",
  generateUrl: "/api/generate-3d-abdominal-wall",
  regenerateUrl: "/api/regenerate-3d-abdominal-wall-panel",
  taskId: "abdominal-wall-3d",
  taskTitle: "Generando Suite Pared Abdominal 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD DE PARED ABDOMINAL",
  scorecardBadge: "Scorecard de pared obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar de pared / hernia si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: ABDOMINAL_WALL_TOPOGRAPHY_DIRECTIVE,
  buildScorecardDirectives: buildAbdominalWallDirectivesFromScorecard,
  directivesPlaceholder:
    "Ej: Hernia umbilical de 18 mm con grasa omental reducible — no inventar incarceración ni diástasis ausentes...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla de pared abdominal",
  loadingDetail: "Renderizando capas de pared, orificio herniario, contenido y dinámica con Valsalva.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D Pared Abdominal (${n} Paneles)`,
  fichaTitle: "Ficha clínica pared abdominal",
  summaryLabel: "Resumen de pared",
  summaryField: "wallSummary",
  morphologyLabel: "Morfología del defecto",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Capas / fascia",
  domainStatusField: "wallLayersStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-orange-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA DE PARED ABDOMINAL",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D PARED ABDOMINAL Y CORRELACIÓN DE DEFECTOS",
  defaultTableTitle: "TABLA ECOGRÁFICA DE PARED ABDOMINAL:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA DE PARED ABDOMINAL:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN",
    "ESTRUCTURA",
    "DIÁMETRO / DIÁSTASIS",
    "CAPAS / FASCIA",
    "CONTENIDO",
    "REDUCIBILIDAD / VALSALVA",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "structure",
    "sizeOrGap",
    "wallLayers",
    "content",
    "reducibilityOrDynamic",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Umbilical",
    structure: "Fascia / orificio",
    sizeOrGap: "—",
    wallLayers: "Capas conservadas",
    content: "Vacío / grasa",
    reducibilityOrDynamic: "Reducible / Valsalva",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "location"],
  annotationSizeKeys: ["sizeOrGap", "size"],
  regenPlaceholder: "Ej: Orificio umbilical / Valsalva / diástasis — topografía exacta según informe...",
  noReportError: "No hay informe disponible para procesar la suite de pared abdominal.",
  analyzingStep: "Analizando pared abdominal, defectos herniarios y capas fasciales...",
  buildingStep: "Construyendo paneles 3D y ficha de pared abdominal...",
  syncedLabel: (n) => `Suite Pared Abdominal 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Pared Abdominal 3D con IA",
  regenerateLabel: "Re-generar Suite Pared Abdominal Completa",
  processingLabel: "Procesando Suite Pared Abdominal...",
  suggestTitle: "Propone etiquetas desde la ficha de pared abdominal",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "location"], ["sizeOrGap", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "location"], ["sizeOrGap", "size"]),
};

export const scrotumSuiteConfig: OrganSuiteConfig = {
  id: "scrotum",
  accent: "amber",
  title: "Suite Escroto 3D & Ficha Escrotal",
  badge: "Escroto Pro",
  subtitle: "Reconstrucción 3D de testículos, epidídimo, cordón y Doppler escrotal",
  studyTypeLabel: "Tipo de estudio de escroto",
  studyTypes: [
    { value: "scrotum_acute", label: "Agudo (torsión / epidídimo-orquitis)" },
    { value: "scrotum_chronic", label: "Crónico (varicocele / hidrocele)" },
    { value: "scrotum_mass", label: "Masa testicular / extratesticular" },
    { value: "general_scrotum", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) =>
    detectByKeywords(
      r,
      p,
      [
        {
          value: "scrotum_acute",
          keys: [
            "torsion",
            "torsión",
            "orquitis",
            "epididimo-orquitis",
            "epidídimo-orquitis",
            "epididimoorquitis",
            "agudo",
            "aguda",
          ],
        },
        {
          value: "scrotum_chronic",
          keys: ["varicocele", "hidrocele", "cronico", "crónico", "cronica", "crónica"],
        },
        {
          value: "scrotum_mass",
          keys: ["masa", "tumor", "neoplasia", "nodulo", "nódulo", "lesion focal", "lesión focal"],
        },
        {
          value: "general_scrotum",
          keys: ["escroto", "escrotal", "testiculo", "testículo", "epididimo", "epidídimo"],
        },
      ],
      "general_scrotum"
    ),
  studyTypeBodyKey: "scrotumType",
  generateUrl: "/api/generate-3d-scrotum",
  regenerateUrl: "/api/regenerate-3d-scrotum-panel",
  taskId: "scrotum-3d",
  taskTitle: "Generando Suite Escroto 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD DE ESCROTO",
  scorecardBadge: "Scorecard de escroto obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar escrotal si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: SCROTUM_TOPOGRAPHY_DIRECTIVE,
  buildScorecardDirectives: buildScrotumDirectivesFromScorecard,
  directivesPlaceholder:
    "Ej: Testículo derecho homogéneo 4,2×2,8×2,5 cm; Doppler hiliar presente — no inventar torsión ni masa ausentes...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla escrotal",
  loadingDetail: "Renderizando testículos, epidídimo, cordón y flujo Doppler según el informe.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D Escroto (${n} Paneles)`,
  fichaTitle: "Ficha clínica escrotal",
  summaryLabel: "Resumen escrotal",
  summaryField: "scrotumSummary",
  morphologyLabel: "Morfología testicular / epididimaria",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Doppler / vascular",
  domainStatusField: "dopplerVascularStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-orange-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA DE ESCROTO",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D ESCROTO Y CORRELACIÓN ANATOMOPATOLÓGICA",
  defaultTableTitle: "TABLA ECOGRÁFICA DE ESCROTO:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA ESCROTAL:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LADO / SITIO",
    "ESTRUCTURA",
    "TAMAÑO / VOLUMEN",
    "ECOPATRÓN",
    "DOPPLER / VASCULAR",
    "LÍQUIDO / MASA",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "sideOrSite",
    "structure",
    "sizeOrVolume",
    "echoPattern",
    "vascularOrDoppler",
    "fluidOrMass",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    sideOrSite: "Testículo derecho",
    structure: "Parénquima testicular",
    sizeOrVolume: "—",
    echoPattern: "Homogéneo",
    vascularOrDoppler: "Flujo hiliar presente",
    fluidOrMass: "Sin hidrocele significativo",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "sideOrSite"],
  annotationSizeKeys: ["sizeOrVolume", "sizeOrThickness", "size"],
  regenPlaceholder:
    "Ej: Testículo derecho / Doppler hiliar / varicocele izquierdo — topografía exacta según informe...",
  noReportError: "No hay informe disponible para procesar la suite de escroto.",
  analyzingStep: "Analizando escroto, parénquima testicular, epidídimo y Doppler...",
  buildingStep: "Construyendo paneles 3D y ficha escrotal...",
  syncedLabel: (n) => `Suite Escroto 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Escroto 3D con IA",
  regenerateLabel: "Re-generar Suite Escroto Completa",
  processingLabel: "Procesando Suite Escroto...",
  suggestTitle: "Propone etiquetas desde la ficha escrotal",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "sideOrSite"], ["sizeOrVolume", "sizeOrThickness", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "sideOrSite"], ["sizeOrVolume", "sizeOrThickness", "size"]),
};

export const muscleTendonSuiteConfig: OrganSuiteConfig = {
  id: "muscle-tendon",
  accent: "rose",
  title: "Suite Muscular / Tendinosa 3D & Ficha Músculo-Tendón",
  badge: "Músculo-Tendón Pro",
  subtitle: "Reconstrucción 3D de desgarros musculares, uniones miotendinosas y tendones (p. ej. Aquiles)",
  studyTypeLabel: "Tipo de estudio de músculo-tendón",
  studyTypes: [
    { value: "lesion_muscular", label: "Lesión muscular / desgarro" },
    { value: "union_miotendinosa", label: "Unión miotendinosa / MTJ" },
    { value: "aquiles_tendon", label: "Tendón de Aquiles" },
    { value: "general_musculo_tendon", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) => {
    const text = `${r || ""} ${p || ""}`.toLowerCase();
    if (/aquiles|achilles|tend[oó]n de aquiles/.test(text)) return "aquiles_tendon";
    if (/miotendin|uni[oó]n miotendinosa|myotendinous|\bmtj\b/.test(text)) return "union_miotendinosa";
    if (
      /desgarro|rotura muscular|lesi[oó]n muscular|peetrons|isquiotibial|gemelo|gastrocnemio|s[oó]leo|cu[aá]driceps|rectus femoris|aductor/.test(
        text
      )
    )
      return "lesion_muscular";
    return "general_musculo_tendon";
  },
  studyTypeBodyKey: "muscleTendonType",
  generateUrl: "/api/generate-3d-muscle-tendon",
  regenerateUrl: "/api/regenerate-3d-muscle-tendon-panel",
  taskId: "muscle-tendon-3d",
  taskTitle: "Generando Suite Muscular / Tendinosa 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD MÚSCULO-TENDÓN",
  scorecardBadge: "Scorecard de músculo-tendón obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar de lesión muscular si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: MUSCLE_TENDON_TOPOGRAPHY_DIRECTIVE,
  buildScorecardDirectives: buildMuscleTendonDirectivesFromScorecard,
  directivesPlaceholder:
    "Ej: Desgarro isquiotibial derecho en MTJ con gap 8 mm y hematoma; Aquiles midportion intacto — no inventar rotura completa ausente...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla escrotal",
  loadingDetail: "Renderizando vientre muscular, MTJ, tendón y hematoma/retracción según el informe.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D Músculo-Tendón (${n} Paneles)`,
  fichaTitle: "Ficha clínica músculo-tendón",
  summaryLabel: "Resumen músculo-tendón",
  summaryField: "muscleTendonSummary",
  morphologyLabel: "Morfología muscular / tendinosa",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Desgarro / tendón",
  domainStatusField: "tearTendonStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-orange-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA MÚSCULO-TENDÓN",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D MÚSCULO-TENDÓN Y CORRELACIÓN ANATOMOPATOLÓGICA",
  defaultTableTitle: "TABLA ECOGRÁFICA MÚSCULO-TENDÓN:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA MÚSCULO-TENDINOSA:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LOCALIZACIÓN / LADO",
    "ESTRUCTURA",
    "GROSOR / GAP",
    "ECOPATRÓN",
    "HEMATOMA / LÍQUIDO",
    "DINÁMICA / RETRACCIÓN",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "structure",
    "thicknessOrGap",
    "echoPattern",
    "hematomaOrFluid",
    "dynamicFinding",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Pantorrilla derecha",
    structure: "Unión miotendinosa / vientre muscular",
    thicknessOrGap: "—",
    echoPattern: "Desgarro parcial / tendinopatía",
    hematomaOrFluid: "Sin colección significativa",
    dynamicFinding: "Sin retracción franca",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "location"],
  annotationSizeKeys: ["sizeOrThickness", "size"],
  regenPlaceholder:
    "Ej: Isquiotibial derecho MTJ / Aquiles midportion / gap y retracción — topografía exacta según informe...",
  noReportError: "No hay informe disponible para procesar la suite de músculo-tendón.",
  analyzingStep: "Analizando lesión muscular/tendinosa, MTJ, Aquiles y dinámica...",
  buildingStep: "Construyendo paneles 3D y ficha músculo-tendón...",
  syncedLabel: (n) => `Suite Muscular / Tendinosa 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Muscular / Tendinosa 3D con IA",
  regenerateLabel: "Re-generar Suite Muscular / Tendinosa Completa",
  processingLabel: "Procesando Suite Muscular / Tendinosa...",
  suggestTitle: "Propone etiquetas desde la ficha músculo-tendón",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
};

export const wristSuiteConfig: OrganSuiteConfig = {
  id: "wrist",
  accent: "sky",
  title: "Suite Muñeca 3D & Ficha de Muñeca",
  badge: "MSK Pro",
  subtitle: "Reconstrucción 3D de tendones, TFCC, túnel del carpo y ligamentos carpianos",
  studyTypeLabel: "Tipo de estudio de muñeca",
  studyTypes: [
    { value: "tenosinovitis_dorsal", label: "Tenosinovitis / tendones dorsales" },
    { value: "tunel_carpiano", label: "Túnel del carpo / flexores" },
    { value: "tfcc_ligamentos", label: "TFCC / ligamentos carpianos" },
    { value: "general_muneca", label: "General / detectar del informe" },
  ],
  detectStudyType: (r, p) => {
    const text = `${r || ""} ${p || ""}`.toLowerCase();
    if (
      /tfcc|triangulo fibrocartilaginoso|fibrocart[ií]lago triangular|ligamento escafolunar|escafolunar|lunotriquet|carpiano distal/.test(
        text
      )
    )
      return "tfcc_ligamentos";
    if (
      /t[uú]nel del carpo|carpal tunnel|mediano|flexor digitorum|flexores|retin[aá]culo flexor/.test(text)
    )
      return "tunel_carpiano";
    if (
      /tenosinovit|compartimento|extensor|de quervain|dequervain|ecu|extensor carpi|dorsal de mu[nñ]eca/.test(text)
    )
      return "tenosinovitis_dorsal";
    return "general_muneca";
  },
  studyTypeBodyKey: "wristType",
  generateUrl: "/api/generate-3d-wrist",
  regenerateUrl: "/api/regenerate-3d-wrist-panel",
  taskId: "wrist-3d",
  taskTitle: "Generando Suite Muñeca 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD DE MUÑECA",
  scorecardBadge: "Scorecard de muñeca obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard (y radar MSK de muñeca si aplica) se inyectan como directiva obligatoria.",
  topographyDirective: WRIST_TOPOGRAPHY_DIRECTIVE,
  buildScorecardDirectives: buildWristDirectivesFromScorecard,
  directivesPlaceholder:
    "Ej: Tenosinovitis 1er compartimento derecho (De Quervain); TFCC ulnar intacto — no inventar rotura ausente...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla de muñeca",
  loadingDetail: "Renderizando tendones, retináculos, TFCC y topografía carpiana según el informe.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D Muñeca (${n} Paneles)`,
  fichaTitle: "Ficha clínica de muñeca",
  summaryLabel: "Resumen muñeca",
  summaryField: "wristSummary",
  morphologyLabel: "Morfología tendinosa / ligamentaria",
  morphologyField: "morphologyNotes",
  domainStatusLabel: "Tendones / ligamentos",
  domainStatusField: "tendonLigamentStatus",
  domainStatusAccent: "text-yellow-300",
  keyPointsAccent: "text-orange-300",
  hasKeyPoints: true,
  defaultTerritory: "ECOGRAFÍA DE MUÑECA",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D MÚSCULO-TENDÓN Y CORRELACIÓN ANATOMOPATOLÓGICA",
  defaultTableTitle: "TABLA ECOGRÁFICA DE MUÑECA:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA DE MUÑECA:",
  tableProperty: "findingTable",
  defaultColumnHeaders: [
    "LADO / SITIO",
    "ESTRUCTURA",
    "GROSOR / ÁREA",
    "ECOPATRÓN",
    "LÍQUIDO / SINOVIAL",
    "DINÁMICA / ENGATILLAMIENTO",
    "SEVERIDAD",
    "IMPACTO",
  ],
  tableFields: [
    "location",
    "structure",
    "thicknessOrGap",
    "echoPattern",
    "hematomaOrFluid",
    "dynamicFinding",
    "severity",
    "clinicalImpact",
  ],
  newRowDefaults: {
    location: "Muñeca derecha / 1er compartimento",
    structure: "Tendón extensor / retináculo",
    thicknessOrGap: "—",
    echoPattern: "Tenosinovitis leve",
    hematomaOrFluid: "Sin colección significativa",
    dynamicFinding: "Sin engatillamiento",
    severity: "Leve",
    clinicalImpact: "Seguimiento clínico",
  },
  annotationTextKeys: ["structure", "location"],
  annotationSizeKeys: ["sizeOrThickness", "size"],
  regenPlaceholder:
    "Ej: 1er compartimento derecho / túnel del carpo / TFCC ulnar — topografía exacta según informe...",
  noReportError: "No hay informe disponible para procesar la suite de muñeca.",
  analyzingStep: "Analizando tendones, túnel del carpo, TFCC y ligamentos de muñeca...",
  buildingStep: "Construyendo paneles 3D y ficha de muñeca...",
  syncedLabel: (n) => `Suite Muñeca 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Muñeca 3D con IA",
  regenerateLabel: "Re-generar Suite Muñeca Completa",
  processingLabel: "Procesando Suite Muñeca...",
  suggestTitle: "Propone etiquetas desde la ficha de muñeca",
  attachSuggestions: (d) =>
    genericAttach(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "findingTable", ["structure", "location"], ["sizeOrThickness", "size"]),
};

export const vascularSuiteConfig: OrganSuiteConfig = {
  id: "vascular",
  accent: "indigo",
  title: "Suite Vascular 3D & Mapa Ánatomo-Hemodinámico",
  badge: "Doppler Pro",
  subtitle:
    "Reconstrucción macrovascular 3D de alta fidelidad, cálculo de estenosis y tabulación de velocidades",
  studyTypeLabel: "Territorio Vascular",
  studyTypes: [
    { value: "carotideo_vertebral", label: "Doppler Carotídeo y Vertebral" },
    { value: "arterial_mmii", label: "Doppler Arterial Miembro Inferior" },
    { value: "venoso_mmii", label: "Doppler Venoso Miembro Inferior" },
    { value: "arterias_renales", label: "Doppler de Arterias Renales" },
    { value: "aorto_iliaco", label: "Doppler Aorto-Ilíaco" },
    { value: "general_vascular", label: "General / Detectar del Informe" },
  ],
  detectStudyType: (r, p) => {
    const text = `${(r || "").toLowerCase()} ${(p || "").toLowerCase()}`;
    if (text.includes("carot") || text.includes("vertebr")) return "carotideo_vertebral";
    if (text.includes("venos") || text.includes("trombosis") || text.includes("safena") || text.includes("tvp"))
      return "venoso_mmii";
    if (
      text.includes("arterial") ||
      text.includes("femoral") ||
      text.includes("poplit") ||
      text.includes("tibial")
    )
      return "arterial_mmii";
    if (text.includes("renal") || text.includes("renales")) return "arterias_renales";
    if (text.includes("aort") || text.includes("iliac")) return "aorto_iliaco";
    return "carotideo_vertebral";
  },
  studyTypeBodyKey: "vascularType",
  generateUrl: "/api/generate-3d-vascular",
  regenerateUrl: "/api/regenerate-3d-vascular-panel",
  taskId: "vascular-3d",
  taskTitle: "Generando Suite Vascular 3D",
  scorecardMarker: "DIRECTIVA OBLIGATORIA DEL SCORECARD VASCULAR",
  scorecardBadge: "Scorecard vascular obligatorio",
  scorecardHint:
    "Los criterios activos del Scorecard se inyectan siempre como directiva obligatoria (igual que Atlas / Focal 3D).",
  topographyDirective: "",
  buildScorecardDirectives: buildVascularDirectivesFromScorecard,
  directivesPlaceholder: "Ej: Destacar placa ulcerada en bulbo derecho...",
  emptyHint: "Presiona Generar para construir los modelos 3D y la tabla velocimétrica",
  loadingDetail:
    "Renderizando modelos anatómicos fotorrealistas de los vasos, caracterizando placas y sintetizando índices hemodinámicos.",
  panelsHeading: (n) => `Reconstrucción Volumétrica 3D de Vasos (${n} Paneles)`,
  fichaTitle: "FICHA CLÍNICA HEMODINÁMICA (CORRELACIÓN CON LA FIGURA 3D)",
  summaryLabel: "SÍNTESIS HEMODINÁMICA",
  summaryField: "vascularSummary",
  morphologyLabel: "PARED / PLACA / CIMT",
  morphologyField: "wallPlaqueNotes",
  domainStatusLabel: "VELOCIDADES / ÍNDICES (PSV·EDV·RAR)",
  domainStatusField: "velocityHemodynamicStatus",
  domainStatusAccent: "text-sky-300",
  keyPointsAccent: "text-emerald-300",
  hasKeyPoints: true,
  defaultTerritory: "DOPPLER VASCULAR",
  defaultFigureTitle: "FIGURA 1. ATLAS 3D DE CORRELACIÓN ANATOMOPATOLÓGICA Y HEMODINÁMICA",
  defaultTableTitle: "TABLA HEMODINÁMICA Y CARACTERIZACIÓN DE LESIONES:",
  defaultSynthesisTitle: "SÍNTESIS MORFOLÓGICA Y HEMODINÁMICA:",
  tableProperty: "hemodynamicTable",
  defaultColumnHeaders: [
    "VASO / SEGMENTO",
    "PLACA / TROMBO",
    "% ESTENOSIS",
    "PATRÓN (PSV/EDV)",
    "REL. / ÍNDICE",
    "IMPACTO HEMODIN.",
  ],
  tableFields: [
    "vessel",
    "plaqueOrThrombus",
    "stenosisPercent",
    "patternOrVelocity",
    "hemodynamicIndex",
    "clinicalImpact",
  ],
  newRowDefaults: {
    vessel: "Nuevo Segmento Vascular",
    plaqueOrThrombus: "Morfología evaluada",
    stenosisPercent: "0%",
    patternOrVelocity: "Laminar normal",
    hemodynamicIndex: "Normal",
    clinicalImpact: "Sin repercusión",
  },
  annotationTextKeys: ["vessel", "plaqueOrThrombus"],
  annotationSizeKeys: ["stenosisPercent", "patternOrVelocity"],
  regenPlaceholder: "Ej: Mostrar trombo oclusivo más oscuro...",
  noReportError: "No hay informe disponible para procesar el mapa vascular.",
  analyzingStep: "Analizando parámetros velocimétricos y territorio vascular...",
  buildingStep: "Construyendo matriz hemodinámica y prompts macro-vasculares 3D...",
  syncedLabel: (n) => `Suite Vascular 3D sincronizada (${n} paneles generados)`,
  generateLabel: "Generar Suite Vascular 3D con IA",
  regenerateLabel: "Re-generar Suite Vascular Completa",
  processingLabel: "Procesando Suite Vascular...",
  suggestTitle: "Propone etiquetas desde la tabla hemodinámica",
  attachSuggestions: (d) =>
    genericAttach(d, "hemodynamicTable", ["vessel", "plaqueOrThrombus"], ["stenosisPercent", "patternOrVelocity"]),
  suggestMore: (d) =>
    genericSuggestMore(d, "hemodynamicTable", ["vessel", "plaqueOrThrombus"], ["stenosisPercent", "patternOrVelocity"]),
};
